### ISSUE TITLE
Add TCL (Lyon) subway stations geojson

### ISSUE THREAD

**Issue by bnjbvr** [Phyks/Flatisfy#1]
It'd be great to have public transportation information for other cities than Paris: for Lyon, it seems there is some data available there: https://data.grandlyon.com/equipements/points-darrft-du-rfseau-tcl/

**Comment by Phyks** [comment]
Sure, I'll have a look at it ASAP!

**Comment by bnjbvr** [comment]
Closed in favor of https://git.phyks.me/Phyks/flatisfy/issues/58
