### ISSUE TITLE
Queries made with more than 3 cities

### ISSUE THREAD

**Issue by Hatrix42** [Phyks/Flatisfy#10]
I noticed some queries were made with more than 3 cities, thus websites discarding those cities.
Conf : http://paste.awesom.eu/EU2A
Example : http://htx.fr/images/2017-24-10_20-03-11.png

**Comment by Phyks** [comment]
Ok, so this is a bug from `logicimmo` module for Weboob, which does not support well the case where multiple cities have the same postal code.

For instance, for postal code 92140, it returns

```
[u'TOUTES-COMMUNES-92140', u'CLAMART-92140', u'LE-PETIT-CLAMART-92140']
```

which counts for three cities. It should only be using the first `TOUTES-COMMUNES-92140` item though.

**Comment by Phyks** [comment]
Actually, I think it would be better to fix it in Flatisfy directly. I need a bit of reflexion on this though :/

**Comment by Phyks** [comment]
Reopening and keeping this issue open as there might still be a bug with `logicimmo`. I could not test it yet.

Problem is that the latest fix will add *all* cities, which will include duplicates (as `TOUTES-COMMUNES` is a duplicate with the other two entries). I don't think this should be an issue (at most, there will be some extra deduplication job for Flatisfy), but I should check it.

**Comment by Phyks** [comment]
Completely fixed in latest commit.
