### ISSUE TITLE
Search only working on Followed flats

### ISSUE THREAD

**Issue by Hatrix42** [Phyks/Flatisfy#11]
Search appears to be only working on Followed flats.
Example: http://htx.fr/images/2017-24-10_20-48-26.png

Steps to reproduce the issue:
- search a term with no followed flats
- search again after having followed some flats

**Comment by Phyks** [comment]
Indeed, I can reproduce this. Not sure however why this is happening. I'll try to have a look ASAP, let me know if you want to try to debug it meanwhile.

**Comment by Phyks** [comment]
Hmmm, I've just tried with a clean database and I can no longer reproduce it. Can you confirm you are still able to reproduce it from a clean database (freshly created)?
