### ISSUE TITLE
Invalid map marker position

### ISSUE THREAD

**Issue by bagage** [Phyks/Flatisfy#7]
Say you have multiple cities for a single postal code (rural area) *A*, *B*, *C*: all flats marker are positionned in a single city *A* (the biggest one?), even if `flatisfy.db` location column contains proper city's postal code **and** city's name of the flat.

**Comment by Phyks** [comment]
The original goal of Flatisfy was to help find a new place in densely populated areas. Especially Paris and Lyon, which have been tested so far. Most of its features cannot work in rural areas and actually don't have much sense there. Typically, travel times work by using public transportation data. In rural areas, I think the typical use case would be to use car, and I am not even sure I can get opendata for public transportations.

Postal code is a really nice data as it is (usually) consistent across various datasets, can serve as a unique ID for some geographical area, and is super easy to match and extract. City's name on the contrary are bug prone. See for instance the current mechanism for extracting public transportation stops names. It is cumbersome and misses quite a lot of potential matches actually. City's name are never written the same way, and it would require quite a lot of development.

So, as I'm missing time to develop every feature I would like for Flatisfy, I'd rather focus on main cities. Then, I agree that in rural areas, that will not be the best option, and markers will not be best positionned (I don't think it will be biggest city, just the first match).

I would gladly review and accept any PR to improve support for rural areas!
